services:
    Mikamatto\ReservedValuesBundle\Validator\Constraints\ReservedValuesValidator:
        arguments:
            - '@service_container'
            - '@security.helper'
        tags: ['validator.constraint_validator']